### ISSUE TITLE
F are shown instead of C, when selecting on settings.

### ISSUE THREAD

**Issue by moxi** [moxi/weather-app-demo#43]
![screenshot](https://cloud.githubusercontent.com/assets/437653/19141112/531c1fca-8b47-11e6-82a6-7786e166614a.jpg)

**Comment by perlajarillo** [comment]
I have not been able to duplicate this bug, everything seems fine to me. Is this bug fixed?

**Comment by Mukazuge** [comment]
i replicate this bug in an Android VM from android studio. I have the App from store and it appears to be fine there.

**Comment by moxi** [comment]
This issue has been fixed by #62
